### ISSUE TITLE
Is this module supposed to be documented?

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-import-module#6]
The docs it does have still reference `can-util`: https://github.com/canjs/can-import-module/blob/master/can-import-module.js#L7

Those docs can be found on canjs.com but aren’t part of the sidebar/navigation. I’m wondering if we should hide those docs or update them to document this module.

**Comment by phillipskevin** [comment]
This package isn't used directly by canjs, so I think it would be best to just hide the docs.

**Comment by cherifGsoul** [comment]
Its parent module is hidden, I can not find it in the API sidebar.

**Comment by chasenlehara** [comment]
It shows up when you search for `can-util`
